### ISSUE TITLE
Guidance on downloadable viewable package 

### ISSUE THREAD

**Issue by paulgovan** [Developer-Autodesk/view-and-data-npm#1]
I am looking for a bit more guidance on the downloadable data package as far as how the data is structured, file types (I was not familiar with svf, for example), dependencies, etc. Do you happen to have additional references on managing the data offline? For example, one of my questions is if it would be possible to convert the data package completely to json for compatibility with other programs?

**Comment by leefsmp** [comment]
This is an undocumented file format, we provide you with the code to illustrate how to download and serve them locally but you are on your own playing with it and reverse engineer the structure if you need to. The .pf files contain the geometry information (vertices, faces) in binary format, so it's not possible to convert to simple json.

Sorry for not being more helpful.

**Comment by cyrillef** [comment]
The viewingservice/v1/{{base64encodedurn}}/all will return you a json reply which contains the 1st level of dependencies, that will contain a bunch of .gz / .png / ... files you need to download. Then read the svf manifest file and download the additional entries (the file is compressed, but is a json file). Checkout code at [Node.js extractor](https://github.com/cyrillef/extract-view.and.data.api) for more details.

For the question on converting the viewer bubbles to pure json, have you though of [glTF](https://github.com/KhronosGroup/glTF). It will be still a lot of work for you to do the conversion, but that would be a standard format that any webgl / opengles would support natively.

**Comment by paulgovan** [comment]
Thank @leefsmp and @cyrillef. I'll do some more digging and also check out gITF

**Comment by paulgovan** [comment]
I am primarily interested in accessing and manipulating the material properties of the model. Am I right in assuming that the .svf manifest file references the .db SQLite database?

**Comment by cyrillef** [comment]
Either the SVF file or one of its descendant would since my extractor code catch it. But if you are interested by materials, you would probably want to checkout the Materials.json.gz (you can use the gunzip -d command if you want to test on the command line),

**Comment by paulgovan** [comment]
Awesome! Thanks again @cyrillef
