### ISSUE TITLE
upload error~

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/view-and-data-npm#10]
before was good , just failed
![image](https://cloud.githubusercontent.com/assets/13595509/17548316/ec77fa50-5f1d-11e6-93f2-b322baccfdad.png)

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/17554083/c8ab7b1a-5f3b-11e6-9f33-a9f0d6293a86.png)

**Comment by autodesk-adn** [comment]
It is back to normal, let us know if you still having issues

**Comment by ycjcl868** [comment]
Although the status is right.

![image](https://cloud.githubusercontent.com/assets/13595509/17574460/f73e4aea-5f93-11e6-8779-49a1845e8f4f.png)

But 
![image](https://cloud.githubusercontent.com/assets/13595509/17574453/e0bf564c-5f93-11e6-8dcf-6d1a38eeb330.png)

**Comment by autodesk-adn** [comment]
what is the issue? everything seems ok - also posting programming question on the repo is not the way to get proper support. Issues on the repo, are issues logged against the sample itseld, which isn't the case here. I encourage you to post your programming issue on stackoverflow with the following tags. autodesk-forge autodesk-data-management  - see example here http://stackoverflow.com/questions/38878138/autodesk-forge-viewer-what-is-the-url-for-the-viewer-files-i-e-viewer3d-min-js/38878463#38878463 

I am closing the ticket here, and will answer your question on stackoverflow.

**Comment by ycjcl868** [comment]
upload very slowly  in the website,  
![image](https://cloud.githubusercontent.com/assets/13595509/17589165/b59f18ea-6005-11e6-9dfa-987b2199f671.png)

**Comment by autodesk-adn** [comment]
Again not an issue with the sample or package,, but certainly dependent on your internet bandwidth and/or bandwidth to access Amazon S3 server.

**Comment by ycjcl868** [comment]
How to accelerate the upload speed in China?

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/17641378/ee78ad66-614f-11e6-9a08-e5c2c0dbb3f0.png)

**Comment by ycjcl868** [comment]
![55141d29-964f-47cd-8c19-7c546db21f29](https://cloud.githubusercontent.com/assets/13595509/17641380/fb91f804-614f-11e6-873e-98e861e92ab1.png)
