### ISSUE TITLE
Error Forbidden~~~

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/view-and-data-npm#2]
I run `npm test`,but throw these errors.What should I do?
![image](https://cloud.githubusercontent.com/assets/13595509/15644291/b23d48bc-2684-11e6-96a6-2518962d1255.png)

**Comment by leefsmp** [comment]
The current version "2.0.0" is actually not open to external developers, so you would need to use "1.0.7"

You also have to modify the bucket name in the test because buckets are unique and tied to an account.

Hope that helps
Philippe.

**Comment by ycjcl868** [comment]
my bucket name I created is actually right,  the current  version is node or other program?  I test in the localhost, the issue is common!
![image](https://cloud.githubusercontent.com/assets/13595509/15645329/580ea2cc-268a-11e6-809c-4110fbf5cae9.png)

**Comment by leefsmp** [comment]
I'm talking about the npm package version, for example in your node project, the package.json looks like that:

`"dependencies": {
    ...
    "view-and-data": "1.0.7",
    ...
  },`

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/15646935/19c41a2a-2693-11e6-9b70-657fce5a0488.png) ... I failed.

**Comment by leefsmp** [comment]
You must be doing something wrong, what about the environment variables I mentioned above? Are you able to generate a valid token? 

Post your config file so I can take a look

**Comment by ycjcl868** [comment]
[config-view-and-data.txt](https://github.com/Developer-Autodesk/view-and-data-npm/files/289449/config-view-and-data.txt)
[package.txt](https://github.com/Developer-Autodesk/view-and-data-npm/files/289450/package.txt)

**Comment by cyrillef** [comment]
Hi, I deleted the previous post because you should never share your consumer and secret key with anyone. These keys must be kept very closely to your company. I understand you wanted to show Philippe that your config was right, but again never share these with anyone. If you wanted to share with Philippe, it would be better to share it via email with him. This space on github is public.

**Comment by ycjcl868** [comment]
Thanks~I understand.

**Comment by jaimerosales** [comment]
Hi,

The way I recommend to install the npm is:

npm install view-and-data@1.0.7

Docs on how installing certain version works.
https://docs.npmjs.com/cli/install

That should install you the version that works with non-adsk email accounts.

Try it and let me know.




Sent from my iPhone
On May 30, 2016, at 10:13 AM, ??-King <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks~I understand.

-

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/15700713/41b878c0-2808-11e6-933f-b4002c125340.png)
I really can't do it.

**Comment by leefsmp** [comment]
You need to pay attention to what is the bucketKey which is used during the test, it's a bit misleading

There is the default config in "config-view-and-data.js" but there is also a config object in "test.js", the bucketKey used by the test is this one, so in my test.js:

`
var config = {
  
  defaultBucketKey: 'threejs-bucket'
}

describe('# View & Data Tests: ', function() {

//... rest of the test ...
` 

I run that why the config you gave me and it works fine.

Now that you compromised your credentials, you may want to regenerate your secret key, which is doable from the developer portal, once you open your App

**Comment by ycjcl868** [comment]
When I install the v1.0.7 , I succeed. Thanks ~ By the way, May I know your contact?
![image](https://cloud.githubusercontent.com/assets/13595509/15857987/dd1a5a08-2cf0-11e6-8f6d-84391efaac6c.png)

**Comment by jaimerosales** [comment]
Awesome, glad it worked for you. It can get a bit tricky, apologize for the confusion at the moment. My contact? I'm part of the same team as Cyrille and Phillipe. 

Cheers,
Jaime R.

**Comment by krezeee** [comment]
Well, any idea in my case a bucket fails to pass? Im also on the c9, got the npm view-and-data@1,0,7 and same values as buckets at both config and test file and still got these errors

` # View & Data Tests: 
Token Response:
{ token_type: 'Bearer',
  expires_in: 86399,
  access_token: 'zvYvb33IEvGf6YXbLKrepbayprik' }
    ✓ Get token (646ms)
    1) Get bucket (create if does not exist)
    2) List buckets
    3) Full workflow (bucket/upload/registration/translation/thumbnail)
    4) Download Model Data
    5) Unregister model


  1 passing (31s)
  5 failing

  1) # View & Data Tests:  Get bucket (create if does not exist):
     Error: done() invoked with non-Error: {"error":"Service Unavailable","statusCode":503}
      at onError (test/test.js:69:7)
      at lib$es6$promise$$internal$$tryCatch (node_modules/es6-promise/dist/es6-promise.js:362:16)
      at lib$es6$promise$$internal$$invokeCallback (node_modules/es6-promise/dist/es6-promise.js:374:17)
      at lib$es6$promise$$internal$$publish (node_modules/es6-promise/dist/es6-promise.js:345:11)
      at lib$es6$promise$$internal$$publishRejection (node_modules/es6-promise/dist/es6-promise.js:295:7)
      at lib$es6$promise$asap$$flush (node_modules/es6-promise/dist/es6-promise.js:119:9)

  2) # View & Data Tests:  List buckets:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) # View & Data Tests:  Full workflow (bucket/upload/registration/translation/thumbnail):
     Error: done() invoked with non-Error: {"error":"Service Unavailable","statusCode":503}
      at onError (test/test.js:142:7)
      at lib$es6$promise$$internal$$tryCatch (node_modules/es6-promise/dist/es6-promise.js:362:16)
      at lib$es6$promise$$internal$$invokeCallback (node_modules/es6-promise/dist/es6-promise.js:374:17)
      at lib$es6$promise$$internal$$publish (node_modules/es6-promise/dist/es6-promise.js:345:11)
      at lib$es6$promise$$internal$$publishRejection (node_modules/es6-promise/dist/es6-promise.js:295:7)
      at lib$es6$promise$asap$$flush (node_modules/es6-promise/dist/es6-promise.js:119:9)

  4) # View & Data Tests:  Download Model Data:
     Error: done() invoked with non-Error: Invalid translation, abort download...
      at onInitialized (test/test.js:262:9)
      at lib$es6$promise$$internal$$tryCatch (node_modules/es6-promise/dist/es6-promise.js:362:16)
      at lib$es6$promise$$internal$$invokeCallback (node_modules/es6-promise/dist/es6-promise.js:374:17)
      at lib$es6$promise$$internal$$publish (node_modules/es6-promise/dist/es6-promise.js:345:11)
      at lib$es6$promise$asap$$flush (node_modules/es6-promise/dist/es6-promise.js:119:9)

  5) # View & Data Tests:  Unregister model:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.`

**Comment by leefsmp** [comment]
I've never seen {"error":"Service Unavailable","statusCode":503} error before, could be a temporary server failure ...

Anyway I've updated the package to 2.0.1, which takes into account scopes now, this is required for newly requested credentials. Can you give it a try and let me know.

When running the test, make sure to set your own credentials and unique bucket name in the config:

`//only fill up requested fields, other fields are defaulted
var config = {

  // change that bucket name
  defaultBucketKey: 'leefsmp-forge-transient',

  // change that to your own keys or system variables
  credentials: {

    clientId: process.env.FORGE_CLIENTID,
    clientSecret: process.env.FORGE_CLIENTSECRET
  },

  // see: https://developer.autodesk.com/en/docs/oauth/v2/overview/scopes
  scope: [
    'data:read',
    'data:create',
    'data:write',
    'bucket:read',
    'bucket:create'
  ]
}`
