### ISSUE TITLE
The 'Access-Control-Allow-Origin' issue

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/view-and-data-npm#8]
![image](https://cloud.githubusercontent.com/assets/13595509/17286716/d42f51b8-57fd-11e6-9d67-d3b656c9d492.png)

**Comment by leefsmp** [comment]
This is not an issue concerning the NPM package, but rather loading a model in the viewer. Try clearing your cache and reload. I will close unless you provide explicit details why it is an issue on view-and-data npm package
