### ISSUE TITLE
load the Extension Material error~

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/view-and-data-npm#9]
When I loaded the Material extension, like this:
![image](https://cloud.githubusercontent.com/assets/13595509/17426649/719f0770-5b0c-11e6-8ccc-591bd4bbedc7.png)

![image](https://cloud.githubusercontent.com/assets/13595509/17426651/7a8c0608-5b0c-11e6-84ce-3750d45f3c76.png)

But failed~
![image](https://cloud.githubusercontent.com/assets/13595509/17426593/0ec520b2-5b0c-11e6-856d-7e8040385c30.png)

I tried to load the `requirejs`:
`<script src="/bower_components/requirejs/require.js"></script>`

But failed too:
![image](https://cloud.githubusercontent.com/assets/13595509/17426681/c4f361b4-5b0c-11e6-940d-6fe619804093.png)

**Comment by yiskang** [comment]
Hi @ycjcl868 ,

This is nothing about this repository, I advance you move this post into here (  [library-javascript-viewer-extensions](https://github.com/Developer-Autodesk/library-javascript-viewer-extensions) or [View and Data API - Autodesk Community](http://forums.autodesk.com/t5/view-and-data-api/bd-p/95) ).
